<a href="https://colab.research.google.com/github/tejaswinimaddireddy678-web/Data-science-/blob/matrixes/matrixes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])


In [4]:
result=mat1+mat2
print(result)

[[ 6  8]
 [10 12]]


In [5]:
result=mat2-mat1
print(result)

[[4 4]
 [4 4]]


In [6]:
result=mat1*mat2
print(result)

[[ 5 12]
 [21 32]]


In [8]:
result=np.matmul(mat1,mat2)
print(result)
result=mat1@mat2
print(result)
result=np.dot(mat1,mat2)
print(result)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [9]:
result=mat1/mat2
print(result)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [10]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
print(mat.shape)

(2, 3)


In [12]:
identity=np.eye(3)
print(identity)
identity=np.eye(2)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


In [13]:
mat=np.array([[1,2],[3,4]])
print(np.linalg.det(mat))

-2.0000000000000004


In [16]:
mat=np.array([[1,2],[3,4]])
print(np.linalg.inv(mat))

[[-2.   1. ]
 [ 1.5 -0.5]]
